---
- name: Configuring of the grub file
  hosts: all
  become: yes


  tasks:
  - name: Changing of the grub file
    lineinfile:
            path: /etc/default/grub
            regexp: GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 nvme_core.io_timeout=4294967295 rd.emergency=poweroff rd.shell=0"
            line: GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 nvme_core.io_timeout=4294967295 rd.emergency=poweroff rd.shell=0"

  - name: restart of the grub
    shell: 'grub2-mkconfig'

