---
# handlers file for web_site
#
- name: Restart httpd
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart apache2
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
